services:
  postgres:
    image: postgres:16
    container_name: acp-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employer_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=logical"]

  debezium:
    image: debezium/connect:2.5
    container_name: acp-debezium
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9093
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

  redis:
    image: redis:7
    container_name: acp-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka-native
    container_name: acp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: acp-kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093

  # ollama:
  #   image: ollama/ollama
  #   container_name: acp-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama

  # ollama-init:
  #   image: ollama/ollama
  #   container_name: acp-ollama-init
  #   depends_on:
  #     - ollama
  #   restart: "no"
  #   entrypoint: >
  #     sh -c "sleep 5 && ollama pull qwen2.5:7b"
  #   environment:
  #     OLLAMA_HOST: ollama:11434

  acp-mcp-server:
    build: ./acp-mcp-server
    container_name: acp-mcp-server
    ports:
      - "8000:8000"
    environment:
      MCP_HOST: "0.0.0.0"
      POSTGRES_HOST: postgres
      KAFKA_BOOTSTRAP: kafka:9093
    depends_on:
      - postgres
      - kafka

  acp-gpt:
    build: ./acp-gpt
    container_name: acp-gpt
    ports:
      - "8080:8080"
    environment:
      API_HOST: "0.0.0.0"
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: kafka:9093
      MCP_SERVER_URL: http://acp-mcp-server:8000/mcp
      LLM_BASE_URL: http://host.docker.internal:1234/v1
      # LLM_BASE_URL:http://ollama:11434/v1
    depends_on:
      - redis
      - kafka
      - acp-mcp-server
      - ollama

  debezium-init:
    image: curlimages/curl:latest
    container_name: acp-debezium-init
    depends_on:
      - debezium
    restart: "no"
    entrypoint: >
      sh -c "
        echo 'Waiting for Debezium...';
        until curl -s http://debezium:8083/connectors; do sleep 2; done;
        sleep 5;
        echo 'Registering connector...';
        curl -s -X POST http://debezium:8083/connectors -H 'Content-Type: application/json' -d '{\"name\":\"postgres-connector\",\"config\":{\"connector.class\":\"io.debezium.connector.postgresql.PostgresConnector\",\"database.hostname\":\"postgres\",\"database.port\":\"5432\",\"database.user\":\"admin\",\"database.password\":\"admin\",\"database.dbname\":\"employer_db\",\"topic.prefix\":\"acp\",\"table.include.list\":\"public.employees\",\"plugin.name\":\"pgoutput\",\"slot.name\":\"debezium_slot\"}}';
        echo '';
        echo 'Done.';
      "

volumes:
  pgdata:
  ollama_data:
